services:
  db:
    image: mysql:lts-oracle
    mem_limit: 512m
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "dev"
      MYSQL_DATABASE: findahelper
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: server
    ports:
      - "8080:8080"
    environment:
      - KTOR_ENV=prod
    depends_on:
      - db

  ui:
    build: ./ui
    container_name: ui
    ports:
      - "8085:80"
volumes:
  db_data:
