services:
  db:
    image: mysql:lts-oracle
    mem_limit: 512m
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "dev"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "dev"
      MYSQL_DATABASE: findahelper
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    build:
      context: ../
      dockerfile: ./server/Dockerfile
    container_name: server
    ports:
      - "8080:8080"
    environment:
      - KTOR_ENV=prod
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
