name: Unit Tests (Vite)

runs:
  using: "composite"
  steps:
    - name: Set up Node 22
      uses: actions/setup-node@v4
      with:
        node-version-file: "./ui/package.json"

    - name: Install dependencies
      run: cd ui && npm i
      shell: bash

    - name: Run Unit Tests
      id: run-unit-tests
      shell: bash
      run: |
        cd ui && npm run test &> report.log

    - name: Publish Test Report if Tests failed
      if: ${{ failure() && steps.run-unit-tests.conclusion == 'failure' }}
      uses: ./.github/actions/create-report
      with:
        artifact-path: ui/report.log
        test-type: Vitest
