name: Test and Build Check
on:
  push:
    branches:
      - 'develop'

permissions:
  contents: read
  pull-requests: write

jobs:
  format-and-lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Kotlin format checks
        shell: bash
        run: ./gradlew ktfmtCheck

      - name: Set up Node 22
        uses: actions/setup-node@v4
        with:
          node-version-file: "./ui/package.json"

      - name: Install dependencies
        run: cd ui && npm i
        shell: bash

      - name: Run UI format checks
        shell: bash
        run: |
          cd ui && npm run check

      - name: Run UI lint checks
        shell: bash
        run: |
          cd ui && npm run lint

  test:
    needs: format-and-lint-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Kotlin Unit Tests
        uses: ./.github/actions/unit-tests-kotlin

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Images
        uses: ./.github/actions/build-docker-images
        with:
          push: false
          platform: ${{ matrix.platform }}

